build:
  image: yveshoppe/joomla-systemtests
  commands:
    - composer install --prefer-dist --no-interaction --no-progress
    - cp tests/acceptance.suite.dist.yml tests/acceptance.suite.yml
    - cp RoboFile.dist.ini RoboFile.ini
    - chmod -R 777 *
    - ls -la ..
    - apache2ctl restart
    - mysqld &
    - export DISPLAY=:0
    - Xvfb -screen 0 1024x768x24 -ac +extension GLX +render -noreset > /dev/null 2>&1 &
    - sleep 4 # give xvfb some time to start
    - fluxbox &
    - ./vendor/bin/robo run:tests
    - ./vendor/bin/robo dump:php-version
clone:
  depth: 1
  path: repo
cache:
  mount:
    - vendor
notify:
  email:
    recipients:
      - rdeutz@googlemail.com
    on_success: author
    on_failure: author
